# Generated by Django 4.2.27 on 2026-01-18 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Total do Pedido')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Total de Itens')),
                ('status', models.CharField(choices=[('A', 'Aprovado'), ('C', 'Criado'), ('P', 'Pendente'), ('R', 'Reprovado'), ('E', 'Enviado'), ('F', 'Finalizado')], default='C', max_length=1, verbose_name='Status do Pedido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('product_id', models.PositiveIntegerField(verbose_name='ID do Produto')),
                ('variation_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Variação')),
                ('variation_id', models.PositiveIntegerField(verbose_name='ID da Variação')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
                ('promotional_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Promocional')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('image', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
