# Generated by Django 4.2.27 on 2026-01-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=255, verbose_name='Descrição Curta')),
                ('long_description', models.TextField(verbose_name='Descrição Longa')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('marketing_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Marketing')),
                ('promotional_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Promocional')),
                ('type', models.CharField(choices=[('V', 'Variação'), ('S', 'Simples')], default='V', max_length=1, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Variação')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
                ('promotional_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Promocional')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Estoque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='product.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
            },
        ),
    ]
