# Generated by Django 4.2.27 on 2026-01-24 00:10

from django.db import migrations, models
import utils.files


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_slug_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.files.get_file_path, verbose_name='Imagem de Capa'),
        ),
    ]
