# Generated by Django 4.2.27 on 2026-01-24 00:37

from django.db import migrations, models
import utils.files


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=utils.files.get_file_path, verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
