# Generated by Django 4.2.28 on 2026-02-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='marketing_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promotional_price',
        ),
        migrations.AddField(
            model_name='variation',
            name='sku',
            field=models.CharField(blank=True, help_text='Deixe em branco para gerar automaticamente', max_length=50, null=True, unique=True, verbose_name='SKU (Código único)'),
        ),
    ]
