# Generated by Django 4.2.28 on 2026-02-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_marketing_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('V', 'Variável'), ('S', 'Simples')], default='S', max_length=1, verbose_name='Tipo'),
        ),
    ]
