# Generated by Django 4.2.28 on 2026-02-10 23:30

from django.db import migrations, models
import django.db.models.deletion
import utils.files


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to=utils.files.get_file_path, verbose_name='Imagem')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.variation', verbose_name='Variação')),
            ],
            options={
                'verbose_name': 'Imagem da Variação',
                'verbose_name_plural': 'Imagens das Variações',
                'ordering': ['order'],
            },
        ),
    ]
