# Generated by Django 4.2.29 on 2026-04-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_address_zip_code_alter_profile_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='supplement',
        ),
        migrations.AddField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Complemento'),
        ),
    ]
