# Generated by Django 4.2.29 on 2026-08-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_address_supplement_address_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Endereço Principal'),
        ),
    ]
