# Generated by Django 4.2.29 on 2026-09-10 22:06

from django.db import migrations, models
import utils.files


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_address_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=utils.files.get_file_path, verbose_name='Foto de Perfil'),
        ),
    ]
