# Generated by Django 4.2.29 on 2026-09-11 21:46

import django.core.validators
from django.db import migrations, models
import utils.files


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=utils.files.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'jfif', 'pjpeg', 'pjp'])], verbose_name='Foto de Perfil'),
        ),
    ]
